stages: [test]

playwright_tests:
  stage: test
  image: mcr.microsoft.com/playwright:v1.47.1-jammy
  script:
    - npm ci
    - npx playwright install --with-deps chromium
    - npx playwright test --project=chromium --reporter=line,html
  artifacts:
    when: always
    paths:
      - playwright-report
    expire_in: 7 days
