stages:
  - build
  - test


build_dockerimage:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t playwright-tests .
 


test_playwright:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker run --rm playwright-tests npx playwright test --project=chromium --reporter=line,html
  artifacts:
    when: always
    paths:
      - playwright-report
    expire_in: 7 days
